[workspace]
name = "escapepod-rs"
channels = ["conda-forge"]
platforms = ["linux-64"]

[dependencies]
samtools = "*"
pysam = "*"
pandas = "*"

[activation]
env = { DORADO_VERSION = "1.3.0", PATH = "$PIXI_CACHE_DIR/tools/dorado-$DORADO_VERSION-linux-x64/bin:$PATH" }

[tasks]
install-dorado = """
mkdir -p $PIXI_CACHE_DIR/tools && \
curl -L https://cdn.oxfordnanoportal.com/software/analysis/dorado-$DORADO_VERSION-linux-x64.tar.gz | \
tar -xz -C $PIXI_CACHE_DIR/tools
"""
