"""Type stubs for the native escapepod module."""

from typing import Optional

import numpy as np
import numpy.typing as npt

class Calibration:
    """Calibration parameters for ADC to picoamp conversion."""

    @property
    def offset(self) -> float: ...
    @property
    def scale(self) -> float: ...

class RunInfo:
    """Run information metadata from a POD5 file."""

    @property
    def acquisition_id(self) -> str: ...
    @property
    def acquisition_start_time(self) -> int: ...
    @property
    def adc_max(self) -> int: ...
    @property
    def adc_min(self) -> int: ...
    @property
    def context_tags(self) -> dict[str, str]: ...
    @property
    def experiment_name(self) -> str: ...
    @property
    def flow_cell_id(self) -> str: ...
    @property
    def flow_cell_product_code(self) -> str: ...
    @property
    def protocol_name(self) -> str: ...
    @property
    def protocol_run_id(self) -> str: ...
    @property
    def protocol_start_time(self) -> int: ...
    @property
    def sample_id(self) -> str: ...
    @property
    def sample_rate(self) -> int: ...
    @property
    def sequencing_kit(self) -> str: ...
    @property
    def sequencer_position(self) -> str: ...
    @property
    def sequencer_position_type(self) -> str: ...
    @property
    def software(self) -> str: ...
    @property
    def system_name(self) -> str: ...
    @property
    def system_type(self) -> str: ...
    @property
    def tracking_id(self) -> dict[str, str]: ...

class Read:
    """A single read from a POD5 file."""

    @property
    def read_id(self) -> str: ...
    @property
    def read_number(self) -> int: ...
    @property
    def start_sample(self) -> int: ...
    @property
    def channel(self) -> int: ...
    @property
    def well(self) -> int: ...
    @property
    def pore_type(self) -> str: ...
    @property
    def calibration(self) -> Calibration: ...
    @property
    def calibration_offset(self) -> float: ...
    @property
    def calibration_scale(self) -> float: ...
    @property
    def median_before(self) -> float: ...
    @property
    def end_reason(self) -> str: ...
    @property
    def end_reason_forced(self) -> bool: ...
    @property
    def num_samples(self) -> int: ...
    @property
    def num_minknow_events(self) -> int: ...
    @property
    def sample_rate(self) -> int: ...
    @property
    def run_info(self) -> RunInfo: ...
    @property
    def signal(self) -> npt.NDArray[np.int16]: ...
    @property
    def signal_pa(self) -> npt.NDArray[np.float32]: ...

class Reader:
    """A reader for POD5 files."""

    def __init__(self, path: str) -> None: ...
    @property
    def num_reads(self) -> int: ...
    @property
    def num_read_batches(self) -> int: ...
    @property
    def file_identifier(self) -> str: ...
    @property
    def writing_software(self) -> str: ...
    @property
    def pod5_version(self) -> str: ...
    @property
    def run_infos(self) -> list[RunInfo]: ...
    def reads(self, *, selection: Optional[list[str]] = None) -> list[Read]: ...
    def read_ids(self) -> list[str]: ...
    def __len__(self) -> int: ...
    def __enter__(self) -> "Reader": ...
    def __exit__(
        self,
        exc_type: object = None,
        exc_val: object = None,
        exc_tb: object = None,
    ) -> bool: ...

def open(path: str) -> Reader: ...
