// SPDX-License-Identifier: MIT

//! Parity of the charging feature chain against the reference
//! implementation (`escapepod_models.charging`, which built the training
//! corpus). Golden vectors are generated by
//! `tests/fixtures/gen_charging_golden.py` from leech's tRNA fixtures;
//! floats travel as IEEE-754 bit patterns.
//!
//! Contract: the anchoring chain (spans, orientation, mask boundary, NaN
//! pattern) and dwell are exact; mean/std/resid may differ from NumPy by
//! reduction rounding only (sequential f64 vs pairwise/SIMD summation —
//! bounded here at 1e-4 absolute, observed orders tighter), and the final
//! probability within 1e-6 with identical `cl` bytes.

use escapepod_classify::anchor::{AnchoredRead, finalize, scan_record};
use escapepod_classify::{
    ChargingBundle, Orientation, OrientationVotes, ScanOutcome, cl_from_probability,
    expected_levels_z, junction_features, junction_positions, resolve_orientation,
};
use escapepod_demux::GbmPredictor;
use noodles_bam as bam;
use serde_json::Value;
use std::collections::HashMap;
use std::path::{Path, PathBuf};

fn fixtures() -> PathBuf {
    Path::new(env!("CARGO_MANIFEST_DIR")).join("tests/fixtures")
}

fn golden() -> Value {
    let text = std::fs::read_to_string(fixtures().join("charging_golden.json")).unwrap();
    serde_json::from_str(&text).unwrap()
}

/// Scan the fixture BAM into deduped anchored reads + resolved orientation.
fn scan_fixture(bundle: &ChargingBundle) -> (HashMap<uuid::Uuid, AnchoredRead>, Orientation) {
    let geometry = junction_positions(
        &fixtures().join("trna_reference.fa"),
        &bundle.anchor.motif,
        bundle.anchor.motif_offset,
        &bundle.anchor.common_arm,
    )
    .unwrap();

    let file = std::fs::File::open(fixtures().join("trna_mappings_padded.bam")).unwrap();
    let mut reader = bam::io::Reader::new(file);
    let header = reader.read_header().unwrap();
    let ref_names: Vec<String> = header
        .reference_sequences()
        .keys()
        .map(|k| k.to_string())
        .collect();

    let mut votes = OrientationVotes::default();
    let mut anchored: HashMap<uuid::Uuid, AnchoredRead> = HashMap::new();
    let mut record = noodles_sam::alignment::RecordBuf::default();
    loop {
        if reader.read_record_buf(&header, &mut record).unwrap() == 0 {
            break;
        }
        let Some(ref_name) = record
            .reference_sequence_id()
            .and_then(|id| ref_names.get(id))
        else {
            continue;
        };
        if let ScanOutcome::Anchored(read) =
            scan_record(&record, ref_name, &geometry, &bundle.offsets, 1)
        {
            votes.add(&read);
            let e = anchored.entry(read.read_id);
            match e {
                std::collections::hash_map::Entry::Occupied(mut o) => {
                    if read.mapq > o.get().mapq {
                        o.insert(*read);
                    }
                }
                std::collections::hash_map::Entry::Vacant(v) => {
                    v.insert(*read);
                }
            }
        }
    }
    // The padded fixture carries >= 50 informative reads by construction.
    let orientation = resolve_orientation(&votes, 50).unwrap();
    (anchored, orientation)
}

#[test]
fn charging_chain_matches_reference() {
    let bundle = ChargingBundle::load(&fixtures().join("bundle")).unwrap();
    assert_eq!(bundle.columns.len(), 100);
    assert_eq!(bundle.offsets.len(), 25);
    assert!(bundle.kmer.is_some(), "fixture recipe uses residuals");
    assert!(bundle.operating_point.is_some());

    let g = golden();
    let (anchored, orientation) = scan_fixture(&bundle);

    // Orientation must match what the reference detected on the same BAM.
    let want_orientation = match g["orientation"].as_str().unwrap() {
        "reversed" => Orientation::Reversed,
        _ => Orientation::Time,
    };
    assert_eq!(orientation, want_orientation);

    // POD5 signal index.
    let reader = escapepod_signal::Reader::open(fixtures().join("trna_reads.pod5")).unwrap();
    let mut pod5: HashMap<uuid::Uuid, (f32, f32, Vec<u64>)> = HashMap::new();
    for batch in reader.read_batches().unwrap() {
        let batch = batch.unwrap();
        let view = escapepod_signal::ReadsBatchView::new(&batch, false).unwrap();
        for row in 0..view.num_rows() {
            let read = view.read(row).unwrap();
            pod5.insert(
                read.read_id,
                (
                    read.calibration_offset,
                    read.calibration_scale,
                    read.signal_rows,
                ),
            );
        }
    }
    let extractor = reader.signal_extractor().unwrap();

    let predictor = GbmPredictor::new(&bundle.gbm);
    let kmer = bundle.kmer.as_ref().unwrap();

    let reads = g["reads"].as_array().unwrap();
    assert!(reads.len() >= 15);
    let mut max_dev = 0.0f64;
    for gr in reads {
        let id: uuid::Uuid = gr["read_id"].as_str().unwrap().parse().unwrap();
        let read = anchored
            .get(&id)
            .unwrap_or_else(|| panic!("golden read {id} not anchored"));
        let (offset, scale, rows) = pod5.get(&id).expect("golden read has signal");
        let raw = extractor.get_signal(rows).unwrap();
        assert_eq!(raw.len() as i64, read.ns, "ns tag vs signal length");
        let sig_pa: Vec<f32> = raw
            .iter()
            .map(|&adc| (adc as f32 + offset) * scale)
            .collect();

        let coords = finalize(read, orientation, &bundle.offsets);
        let expected = expected_levels_z(
            &read.seq,
            &kmer.map,
            kmer.k,
            kmer.center_idx,
            &read.qf,
            read.nb,
        );
        let grid = junction_features(&sig_pa, &coords, Some(&expected));

        let want: Vec<f32> = gr["features_bits"]
            .as_array()
            .unwrap()
            .iter()
            .map(|v| f32::from_bits(v.as_u64().unwrap() as u32))
            .collect();
        assert_eq!(grid.len(), want.len());
        for (i, (&got, &w)) in grid.iter().zip(&want).enumerate() {
            let stat = escapepod_classify::FEAT_STATS[i % 4];
            if w.is_nan() || got.is_nan() {
                assert!(
                    w.is_nan() && got.is_nan(),
                    "read {id} feature {i} ({stat}): NaN mask differs ({got} vs {w})"
                );
                continue;
            }
            if stat == "dwell" {
                assert_eq!(got, w, "read {id} feature {i}: dwell must be exact");
                continue;
            }
            let dev = (got as f64 - w as f64).abs();
            max_dev = max_dev.max(dev);
            assert!(
                dev <= 1e-4,
                "read {id} feature {i} ({stat}): {got} vs {w} (dev {dev:e})"
            );
        }

        // Probability + cl.
        let features = bundle.select_columns(&grid);
        let (probs, _) = predictor.predict(&features).unwrap();
        let p = probs[1];
        let p_ref = f64::from_bits(gr["p_bits"].as_u64().unwrap());
        assert!(
            (p - p_ref).abs() <= 1e-6,
            "read {id}: P = {p} vs reference {p_ref}"
        );
        assert_eq!(
            cl_from_probability(p) as u64,
            gr["cl"].as_u64().unwrap(),
            "read {id}: cl byte differs"
        );
    }
    // Reduction-rounding headroom check: deviations should sit far below
    // the tolerance, not hug it.
    assert!(
        max_dev <= 1e-5,
        "feature deviations unexpectedly large: {max_dev:e}"
    );
}

#[test]
fn bundle_rejects_tampered_checksums() {
    // Copy the bundle, flip one byte of the GBM file, expect a load error.
    let dir = tempfile::tempdir().unwrap();
    for f in ["metadata.json", "model.gbm.json", "kmer_levels.tsv"] {
        std::fs::copy(fixtures().join("bundle").join(f), dir.path().join(f)).unwrap();
    }
    let gbm = dir.path().join("model.gbm.json");
    let mut bytes = std::fs::read(&gbm).unwrap();
    let last = bytes.len() - 2;
    bytes[last] ^= 0x01;
    std::fs::write(&gbm, bytes).unwrap();
    let err = ChargingBundle::load(dir.path()).unwrap_err().to_string();
    assert!(err.contains("checksum mismatch"), "got: {err}");
}
