//! Parity test: escpod's native GBM tree walk must reproduce sklearn's
//! `HistGradientBoostingClassifier.predict_proba` on a committed fixture.
//!
//! The fixture (`tests/fixtures/gbm/`) is generated by
//! `scripts/_gen_gbm_fixture.py` (sklearn 1.8): `model.json` is the exported
//! tree ensemble, `inputs.csv` holds raw fingerprints, and `expected_probs.csv`
//! holds the reference per-class probabilities. Keeping the expected values
//! committed means `cargo test` needs no Python/sklearn at all.

use escapepod_demux::{GbmPredictor, load_gbm_model};
use std::path::Path;

fn data_dir() -> std::path::PathBuf {
    Path::new(env!("CARGO_MANIFEST_DIR")).join("tests/fixtures/gbm")
}

/// Parse a simple headered CSV of f64 into rows.
fn read_csv_rows(path: &Path) -> Vec<Vec<f64>> {
    let text = std::fs::read_to_string(path).unwrap();
    text.lines()
        .skip(1) // header
        .filter(|l| !l.trim().is_empty())
        .map(|l| {
            l.split(',')
                .map(|v| v.trim().parse::<f64>().unwrap())
                .collect()
        })
        .collect()
}

#[test]
fn matches_sklearn_predict_proba() {
    let dir = data_dir();
    let model = load_gbm_model(&dir.join("model.json")).expect("load fixture model");
    let predictor = GbmPredictor::new(&model);

    let inputs = read_csv_rows(&dir.join("inputs.csv"));
    let expected = read_csv_rows(&dir.join("expected_probs.csv"));
    assert_eq!(inputs.len(), expected.len(), "row count mismatch");
    assert!(!inputs.is_empty(), "fixture has no eval rows");

    let mut max_abs_err = 0.0f64;
    for (i, (fp, exp)) in inputs.iter().zip(&expected).enumerate() {
        let (probs, _result) = predictor.predict(fp).expect("predict");
        assert_eq!(
            probs.len(),
            exp.len(),
            "row {i}: class count {} != expected {}",
            probs.len(),
            exp.len()
        );
        for (k, (&got, &want)) in probs.iter().zip(exp).enumerate() {
            let err = (got - want).abs();
            max_abs_err = max_abs_err.max(err);
            assert!(
                err < 1e-5,
                "row {i} class {k}: got {got}, expected {want} (abs err {err})"
            );
        }
        // softmax output is a normalized distribution.
        let sum: f64 = probs.iter().sum();
        assert!((sum - 1.0).abs() < 1e-9, "row {i}: probs sum to {sum}");
    }
    eprintln!("GBM parity: max abs error vs sklearn = {max_abs_err:e}");
}
